### ISSUE TITLE
fail to suppress the WARNINGs coming from the hsqldb library

### ISSUE THREAD

**Issue by shiqin-liu** [r5py/r5py#365] opened 2023-10-04 19:01 UTC
**Describe the bug**
R5py fails to turn off the WARNINGs coming from the `hsqldb` library, when setting the verbose off; it is a minor issue that would not affect the actual travel time calculation. But would be great to have it fixed.

```
travel_time_matrix_computer.compute_travel_times()

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.hsqldb.persist.RAFileNIO (file:/Users/ssliu/.cache/r5py/r5-v6.9-all.jar) to method java.nio.DirectByteBuffer.cleaner()
WARNING: Please consider reporting this to the maintainers of org.hsqldb.persist.RAFileNIO
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Possible reason/fix**
take a look at this handling of Java logging: https://github.com/r5py/r5py/blob/28146cdce6058a61eab010184551e36569f24d75/src/r5py/util/jvm.py#L89

It looks like r5py turns off logging output from a lot of pieces of r5, including org.hsqldb.persist — but there is a missing , in the list of modules that might be preventing it from working for that one.

**Comment by christophfink** [comment] 2023-10-10 12:46
Thanks for reporting this issue. This is an upstream decision (staying with an older mapdb version), see, e.g., the discussion here: https://github.com/r5py/r5py/issues/263

**Comment by christophfink** [comment] 2023-10-10 12:46
duplicate of #263

**Closed by christophfink** 2023-10-10 12:46 UTC
