### ISSUE TITLE
Add information how to download the given tutorial as a Notebook

### ISSUE THREAD

**Issue by HTenkanen** [r5py/r5py#345] opened 2023-08-24 08:01 UTC
It is not evident for new users, how one can download the Notebook of a given tutorial. We could maybe add a note about where to find the Notebook to the beginning of each tutorial, or add a simple nice button to the start would would do the trick.

**Comment by christophfink** [comment] 2023-08-24 08:22
This is a borderline duplicate of #347 now, or rather a quick fix for what should be properly implemented there

**Comment by christophfink** [comment] 2023-09-05 15:35
![Screenshot from 2023-09-05 18-35-10](https://github.com/r5py/r5py/assets/4998473/1a904b5b-1908-435d-9e1a-879ca4e95e79)
I have this kind of a button - don’t you see it too?

**Closed** 2023-09-05 15:36 UTC
Labels: documentation, enhancement, invalid, feedback
