### ISSUE TITLE
importing r5py causes geopandas to fail to read file

### ISSUE THREAD

**Issue by rickl4** [r5py/r5py#229] opened 2022-10-07 01:44 UTC
**Describe the bug**
When I import r5py, it causes geopandas to fail to read the file. The files gets read fine if I import r5py after geopandas, but its giving me this error.

```python

import r5py
import sys
sys.argv.append(["--max-memory", "32G"])
import os
import geopandas as gpd
from pathlib import Path
import numpy as np

points = gpd.read_file('random_points_5.geojson')

ImportError                               Traceback (most recent call last)
Input In [3], in <cell line: 1>()
----> 1 points = gpd.read_file('random_points_5.geojson')

File ~\Anaconda3\envs\spatial\lib\site-packages\geopandas\io\file.py:236, in _read_file(filename, bbox, mask, rows, engine, **kwargs)
    167 def _read_file(filename, bbox=None, mask=None, rows=None, engine=None, **kwargs):
    168     """
    169     Returns a GeoDataFrame from a file or URL.
    170 
   (...)
    234     by using the encoding keyword parameter, e.g. ``encoding='utf-8'``.
    235     """
--> 236     engine = _check_engine(engine, "'read_file' function")
    238     filename = _expand_user(filename)
    240     from_bytes = False

File ~\Anaconda3\envs\spatial\lib\site-packages\geopandas\io\file.py:107, in _check_engine(engine, func)
    105     _check_pyogrio(func)
    106 elif engine is None:
--> 107     raise ImportError(
    108         f"The {func} requires the 'pyogrio' or 'fiona' package, "
    109         "but neither is installed or imports correctly."
    110         f"\nImporting fiona resulted in: {fiona_import_error}"
    111         f"\nImporting pyogrio resulted in: {pyogrio_import_error}"
    112     )
    114 return engine

ImportError: The 'read_file' function requires the 'pyogrio' or 'fiona' package, but neither is installed or imports correctly.
Importing fiona resulted in: DLL load failed while importing ogrext: The specified procedure could not be found.
Importing pyogrio resulted in: No module named 'pyogrio'
```

Whereas this is fine

```python
import sys
sys.argv.append(["--max-memory", "32G"])
import os
import geopandas as gpd
from pathlib import Path
import numpy as np

points = gpd.read_file('random_points_5.geojson')

import r5py
```

and I can import further spatial files later on in the script, even after importing r5py.

**Environment:**
 - OS: Windows
 - Python package source: conda
 - JDK 11, python 3.9.12, geopandas 0.11.1, fiona 1.8.21, r5py 0.0.4

**Comment by christophfink** [comment] 2022-10-07 07:02
Hi! Thanks for reporting this issue. Which JDK do you have installed, and from which source?

**Comment by christophfink** [comment] 2022-10-08 12:30
The reason I ask this, is that OpenJDK from conda-forge has an upstream (packaging) bug that results in certain libraries (DLLs) being overwritten with wrong versions (see issue #190). Possible workarounds until the problem is fixed upstream include using a system-wide JDK installation (but be careful with multiple ones, seems to become messy easily on Windows).

If you installed a different JDK or from a different source, this might be a whole different bug, and we would need to investigate a bit further.

**Comment by wklumpen** [comment] 2022-10-08 15:42
Hi Rick! Glad to see you're looking to use r5py :)

In addition to @christophfink's question I'd suggest the following:

* Install a global OpenJDK Environment instead of relying on the OpenJDK (note you may need to do some looking around as per issue #231)
* Check your `JAVA_HOME` settings
* As per the doc's suggestion, fire up a totally new environment using `mamba` and the supplied environment file

If OpenJDK is still being installed via the r5py requirements my next suggestion for getting things working to until we can sort these very Windows issues out is to follow the dev install requirements (and you'd also be welcome to contribute - send me a message if you're interested).

**Comment by christophfink** [comment] 2022-11-30 21:08
Duplicate of #190

**Closed by christophfink** 2022-11-30 21:08 UTC
Labels: bug, question
