### ISSUE TITLE
Car-only routing gives a division-by-zero Java error

### ISSUE THREAD

**Issue by dtreich-itdp** [r5py/r5py#230] opened 2022-10-07 22:10 UTC
**Describe the bug**
When I tried using r5py to generate a travel-time matrix for travel by car (not car to transit, car only), I got an error: java.lang.ArithmeticException: java.lang.ArithmeticException: / by zero

Specifically, this happens when I call TravelTimeMatrixComputer.compute_travel_times() with 
'transport_modes':[LegMode.CAR],
'access_modes':[LegMode.CAR],

This didn't happen in r5r, and I have no problem running walk- or bike-only analysis in r5py. 

It's happened in two different geospatial analysis areas, so I think the problem may be with r5py, but I could be doing something wrong.

**To Reproduce**
1. Use data for Providence, RI, [here](https://drive.google.com/drive/u/0/folders/1bDRy8DDMX0lVyq2hgImP8MdRW6VsXyki)
2. Run the script in that folder, or use your own call to compute_travel_times with CAR as the only mode.

**Expected behavior**
The function should run and deliver a travel time matrix for travel by car.

**Environment:**
 - OS: Ubuntu 20.04.4 LTS
 - Python package source: conda
 - Versions of Python, Java Development Kit, Python modules
 - Python 3.9
 - javac 11.0.16 (I think, from javac -version, I'm not certain how to check within conda/python)

**Test data and/or script/notebook**
See above under reproduction

**full traceback**
Traceback (most recent call last):

  File "TravelTimeComputer.java", line 217, in com.conveyal.r5.analyst.TravelTimeComputer.computeTravelTimes

  File "LinkedPointSet.java", line 453, in com.conveyal.r5.streets.LinkedPointSet.eval

Exception: Java Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/tmp/ipykernel_92337/3924675421.py", line 1, in <cell line: 1>
    route_scenario('scenarios/existing_conditions/')

  File "/home/taylor/access/connectome/routing.py", line 123, in route_scenario
    ttm_long = ttm_computer.compute_travel_times()

  File "/home/taylor/anaconda3/envs/gpd/lib/python3.9/site-packages/r5py/r5/travel_time_matrix_computer.py", line 162, in compute_travel_times
    parallel(

  File "/home/taylor/anaconda3/envs/gpd/lib/python3.9/site-packages/joblib/parallel.py", line 1098, in __call__
    self.retrieve()

  File "/home/taylor/anaconda3/envs/gpd/lib/python3.9/site-packages/joblib/parallel.py", line 975, in retrieve
    self._output.extend(job.get(timeout=self.timeout))

  File "/home/taylor/anaconda3/envs/gpd/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value

  File "/home/taylor/anaconda3/envs/gpd/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))

  File "/home/taylor/anaconda3/envs/gpd/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 620, in __call__
    return self.func(*args, **kwargs)

  File "/home/taylor/anaconda3/envs/gpd/lib/python3.9/site-packages/joblib/parallel.py", line 288, in __call__
    return [func(*args, **kwargs)

  File "/home/taylor/anaconda3/envs/gpd/lib/python3.9/site-packages/joblib/parallel.py", line 288, in <listcomp>
    return [func(*args, **kwargs)

  File "/home/taylor/anaconda3/envs/gpd/lib/python3.9/site-packages/r5py/r5/travel_time_matrix_computer.py", line 273, in _travel_times_from_one_origin
    results = travel_time_computer.computeTravelTimes()

java.lang.ArithmeticException: java.lang.ArithmeticException: / by zero

**Comment by christophfink** [comment] 2022-10-08 12:25
Thanks for reporting this issue. We fixed this for the upcoming version (released probably by the end of the month). In the meantime, you can install the trunk (= development version) using, e.g., `pip install git+https://github.com/r5py/r5py.git`, in which the bug is fixed, already.

**Comment by christophfink** [comment] 2022-10-08 12:25
Duplicate of #191

**Closed** 2022-10-08 12:25 UTC

**Comment by christophfink** [comment] 2022-10-08 12:31
(please feel free to reopen this bug, if the problem persists in the development version or the next release)

**Comment by dtreich-itdp** [comment] 2022-10-10 19:55
Thanks, @christophfink! This package is amazing.
